#!/usr/bin/python
import systemgen
import sys
import os

PATH = os.environ['SYSTEMS_DIR']

def main():
    if os.getuid() != 0:
        sys.exit('%s has to be run as root' % sys.argv[0])
    app = systemgen.App(PATH)
    if len(sys.argv) < 3:
        sys.exit("usage: %s system cmd [args]" % sys.argv[0])
    system_name = sys.argv[1]
    app.setup()
    action = sys.argv[2]
    if action == 'up':
        with app.lock:
            system = app.systems[system_name]
            system.up()
    elif action == 'down':
        with app.lock:
            system = app.systems[system_name]
            system.down()
    elif action == 'chroot':
        with app.lock:
            system = app.systems[system_name]
            system.up()
        os.execvp('chroot', ['chroot', system.mountpoint] + (sys.argv[3:] or ['bash']))

if __name__ == '__main__':
    main()
